#BER DataFrame: generated by https://github.com/willy23martin/trasmissioni_digitali/tree/main/parametri-misura-qualita
BER_data_frame = data.frame(
Rb = c(3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000),
  BER = c(2.13333333*10^(-06), 1.60000000*10^(-06), 1.28000000*10^(-06), 1.06666667*10^(-06), 9.14285714*10^(-07), 8.00000000*10^(-07), 7.11111111*10^(-07))
)

nrow(BER_data_frame)
ncol(BER_data_frame)
names(BER_data_frame)
BER_data_frame$BER
BER_data_frame[, c("Rb", "BER")]
BER_data_frame[, 1:2]
BER_data_frame[1:4,]
BER_data_frame$Capacity <- NULL

#Filters:
subset(BER_data_frame, Rb>7*10^6)
head(BER_data_frame)
tail(BER_data_frame)

# Summary:
summary(BER_data_frame)
unique(BER_data_frame$BER)
